import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

import Layout from '../components/Layout'
import Homepage from '../components/Homepage'
import Aboutus from '../components/Aboutus'
import Team from '../components/Team'

import Contac from '../components/Contac'
import Footer from '../components/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Borregos CCM</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

      </Head>
      <main>
        <Layout>
          <Homepage />
          <Aboutus />
          <Team />

          <Contac />
          <Footer />
        </Layout>
      </main>
    </>
  )
}
